default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: chelery_development

test:
  <<: *default
  database: chelery_test

staging:
  <<: *default
  database: chelery_staging
  username: chelery
  password: <%= ENV['CHELERY_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: chelery_production
  username: chelery
  password: <%= ENV['CHELERY_DATABASE_PASSWORD'] %>
